"""empty message

Revision ID: 005cc7a45d7c
Revises: f9a3cc1410b0
Create Date: 2023-11-14 21:20:14.242205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005cc7a45d7c'
down_revision = 'f9a3cc1410b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unown_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unown_letters')
    # ### end Alembic commands ###
