"""empty message

Revision ID: 03f74740d815
Revises: 13c2eb47fd8c
Create Date: 2023-11-16 03:45:58.054946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f74740d815'
down_revision = '13c2eb47fd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn', schema=None) as batch_op:
        batch_op.alter_column('baseEXP',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn', schema=None) as batch_op:
        batch_op.alter_column('baseEXP',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
