"""empty message

Revision ID: 12fad2f70e2f
Revises: 37d5c685a84f
Create Date: 2023-11-14 19:11:35.371732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fad2f70e2f'
down_revision = '37d5c685a84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkmn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.Column('spriteShiny', sa.String(), nullable=True),
    sa.Column('firstType', sa.String(), nullable=False),
    sa.Column('secondType', sa.String(), nullable=True),
    sa.Column('firstAbility', sa.String(), nullable=False),
    sa.Column('secondAbility', sa.String(), nullable=True),
    sa.Column('hiddenAbility', sa.String(), nullable=True),
    sa.Column('baseEXP', sa.Integer(), nullable=False),
    sa.Column('BaseHP', sa.Integer(), nullable=False),
    sa.Column('BaseAtk', sa.Integer(), nullable=False),
    sa.Column('BaseDef', sa.Integer(), nullable=False),
    sa.Column('BaseSpAtk', sa.Integer(), nullable=False),
    sa.Column('BaseSpDef', sa.Integer(), nullable=False),
    sa.Column('BaseSpd', sa.Integer(), nullable=False),
    sa.Column('form', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pkmn')
    # ### end Alembic commands ###
