"""empty message

Revision ID: 13c2eb47fd8c
Revises: 16bd0b19c23a
Create Date: 2023-11-15 02:02:05.211410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c2eb47fd8c'
down_revision = '16bd0b19c23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_team', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pkmn', ['pkmnID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
