"""empty message

Revision ID: 16bd0b19c23a
Revises: 21b7b1391cce
Create Date: 2023-11-14 22:05:43.925357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bd0b19c23a'
down_revision = '21b7b1391cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unown_letters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('spriteShiny', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unown_letters', schema=None) as batch_op:
        batch_op.drop_column('spriteShiny')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
