"""empty message

Revision ID: 21b7b1391cce
Revises: 005cc7a45d7c
Create Date: 2023-11-14 21:38:13.977397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b7b1391cce'
down_revision = '005cc7a45d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseHP', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('baseAtk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('baseDef', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('baseSpAtk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('baseSpDef', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('baseSpd', sa.Integer(), nullable=False))
        batch_op.drop_column('BaseHP')
        batch_op.drop_column('BaseDef')
        batch_op.drop_column('BaseSpAtk')
        batch_op.drop_column('BaseSpDef')
        batch_op.drop_column('BaseAtk')
        batch_op.drop_column('BaseSpd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BaseSpd', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('BaseAtk', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('BaseSpDef', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('BaseSpAtk', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('BaseDef', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('BaseHP', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('baseSpd')
        batch_op.drop_column('baseSpDef')
        batch_op.drop_column('baseSpAtk')
        batch_op.drop_column('baseDef')
        batch_op.drop_column('baseAtk')
        batch_op.drop_column('baseHP')

    # ### end Alembic commands ###
