"""empty message

Revision ID: 37d5c685a84f
Revises: 84c42465d7c2
Create Date: 2023-11-14 01:01:25.829339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d5c685a84f'
down_revision = '84c42465d7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiny', sa.Boolean(), nullable=False))
    op.alter_column('pkmn_team', 'trainerID', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_team', schema=None) as batch_op:
        batch_op.drop_column('shiny')

    # ### end Alembic commands ###
