"""empty message

Revision ID: 40e41ad93543
Revises: 70686f256013
Create Date: 2023-11-20 01:22:36.429779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e41ad93543'
down_revision = '70686f256013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.drop_column('winnerDeclared')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winnerDeclared', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
