"""empty message

Revision ID: 5390b4f3df09
Revises: e0e458a0e5c7
Create Date: 2023-11-17 15:54:44.701346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5390b4f3df09'
down_revision = 'e0e458a0e5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('minHits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maxHits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ailment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ailmentChance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('critRate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drain', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flinchChance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('healing', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maxTurns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minTurns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('statChance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('effect', sa.String(), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_moves', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('effect')
        batch_op.drop_column('statChance')
        batch_op.drop_column('minTurns')
        batch_op.drop_column('maxTurns')
        batch_op.drop_column('healing')
        batch_op.drop_column('flinchChance')
        batch_op.drop_column('drain')
        batch_op.drop_column('critRate')
        batch_op.drop_column('ailmentChance')
        batch_op.drop_column('ailment')
        batch_op.drop_column('maxHits')
        batch_op.drop_column('minHits')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
