"""empty message

Revision ID: 55cfe6679f9d
Revises: 8ea81e9dd31d
Create Date: 2023-11-20 00:30:08.994403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55cfe6679f9d"
down_revision = "8ea81e9dd31d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn", schema=None) as batch_op:
        batch_op.add_column(sa.Column("turnInBattle", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn", schema=None) as batch_op:
        batch_op.drop_column("turnInBattle")

    # ### end Alembic commands ###
