"""empty message

Revision ID: 5cf26d600ca9
Revises: 7f07e9d45faf
Create Date: 2023-11-20 00:59:57.888517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5cf26d600ca9"
down_revision = "7f07e9d45faf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn", schema=None) as batch_op:
        batch_op.add_column(sa.Column("turnDescription", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn", schema=None) as batch_op:
        batch_op.drop_column("turnDescription")

    # ### end Alembic commands ###
