"""empty message

Revision ID: 70686f256013
Revises: d7aae0a07392
Create Date: 2023-11-20 01:21:23.006292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70686f256013'
down_revision = 'd7aae0a07392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winnerDeclared', sa.Boolean(), nullable=False))
        batch_op.drop_column('turnInBattle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turnInBattle', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('winnerDeclared')

    # ### end Alembic commands ###
