"""empty message

Revision ID: 73e9c2bad5af
Revises: 
Create Date: 2023-11-18 22:59:37.954993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73e9c2bad5af"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pkmn",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sprite", sa.String(), nullable=False),
        sa.Column("spriteShiny", sa.String(), nullable=True),
        sa.Column("firstType", sa.String(), nullable=False),
        sa.Column("secondType", sa.String(), nullable=True),
        sa.Column("firstAbility", sa.String(), nullable=False),
        sa.Column("secondAbility", sa.String(), nullable=True),
        sa.Column("hiddenAbility", sa.String(), nullable=True),
        sa.Column("baseEXP", sa.Integer(), nullable=True),
        sa.Column("baseHP", sa.Integer(), nullable=False),
        sa.Column("baseAtk", sa.Integer(), nullable=False),
        sa.Column("baseDef", sa.Integer(), nullable=False),
        sa.Column("baseSpAtk", sa.Integer(), nullable=False),
        sa.Column("baseSpDef", sa.Integer(), nullable=False),
        sa.Column("baseSpd", sa.Integer(), nullable=False),
        sa.Column("spriteBack", sa.String(), nullable=False),
        sa.Column("spriteShinyBack", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pkmn_moves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("power", sa.String(), nullable=True),
        sa.Column("minHits", sa.String(), nullable=True),
        sa.Column("maxHits", sa.String(), nullable=True),
        sa.Column("ailment", sa.String(), nullable=True),
        sa.Column("ailmentChance", sa.String(), nullable=True),
        sa.Column("moveType", sa.String(), nullable=True),
        sa.Column("critRate", sa.String(), nullable=True),
        sa.Column("drain", sa.String(), nullable=True),
        sa.Column("flinchChance", sa.String(), nullable=True),
        sa.Column("healing", sa.String(), nullable=True),
        sa.Column("maxTurns", sa.String(), nullable=True),
        sa.Column("minTurns", sa.String(), nullable=True),
        sa.Column("statChance", sa.String(), nullable=True),
        sa.Column("damageClass", sa.String(), nullable=True),
        sa.Column("accuracy", sa.String(), nullable=True),
        sa.Column("effectChance", sa.String(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("pp", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("effect", sa.String(), nullable=True),
        sa.Column("flavorText", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "unown_letters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("sprite", sa.String(), nullable=False),
        sa.Column("spriteShiny", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userName", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("dateCreated", sa.Date(), nullable=False),
        sa.Column("favoritePkmn", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("userName"),
    )
    op.create_table(
        "damage_moves_learned_by_pokemon",
        sa.Column("pkmn_id", sa.Integer(), nullable=True),
        sa.Column("move_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["move_id"],
            ["pkmn_moves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pkmn_id"],
            ["pkmn.id"],
        ),
    )
    op.create_table(
        "pkmn_team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pkmnID", sa.Integer(), nullable=False),
        sa.Column("trainerID", sa.Integer(), nullable=False),
        sa.Column("shiny", sa.Boolean(), nullable=False),
        sa.Column("chosenMove", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chosenMove"],
            ["pkmn_moves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pkmnID"],
            ["pkmn.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainerID"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status_moves_learned_by_pokemon",
        sa.Column("pkmn_id", sa.Integer(), nullable=True),
        sa.Column("move_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["move_id"],
            ["pkmn_moves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pkmn_id"],
            ["pkmn.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_moves_learned_by_pokemon")
    op.drop_table("pkmn_team")
    op.drop_table("damage_moves_learned_by_pokemon")
    op.drop_table("user")
    op.drop_table("unown_letters")
    op.drop_table("pkmn_moves")
    op.drop_table("pkmn")
    # ### end Alembic commands ###
