"""empty message

Revision ID: 7ef88be2ea0b
Revises: 427c08501e37
Create Date: 2023-11-17 18:09:50.186432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef88be2ea0b'
down_revision = '427c08501e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_moves', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('moveType',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('damageClass',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('target',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('flavorText',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_moves', schema=None) as batch_op:
        batch_op.alter_column('flavorText',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('target',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('pp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('damageClass',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('moveType',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
