"""empty message

Revision ID: 84c42465d7c2
Revises: 0ddf7984d737
Create Date: 2023-11-14 00:20:45.649413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c42465d7c2'
down_revision = '0ddf7984d737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pkmn_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pkmnID', sa.Integer(), nullable=False),
    sa.Column('trainerID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainerID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pkmn_team')
    # ### end Alembic commands ###
