"""empty message

Revision ID: 8ea81e9dd31d
Revises: 5539a4e570c1
Create Date: 2023-11-19 23:46:12.254289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ea81e9dd31d"
down_revision = "5539a4e570c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pkmn_team", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chosenMoveID", sa.Integer(), nullable=True))
        batch_op.drop_constraint("pkmn_team_chosenMove_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "pkmn_moves", ["chosenMoveID"], ["id"])
        batch_op.drop_column("chosenMove")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pkmn_team", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("chosenMove", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "pkmn_team_chosenMove_fkey", "pkmn_moves", ["chosenMove"], ["id"]
        )
        batch_op.drop_column("chosenMoveID")

    # ### end Alembic commands ###
