"""empty message

Revision ID: d7aae0a07392
Revises: 5cf26d600ca9
Create Date: 2023-11-20 01:01:39.797172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7aae0a07392"
down_revision = "5cf26d600ca9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn", schema=None) as batch_op:
        batch_op.drop_column("playerPkmnDamageTaken")
        batch_op.drop_column("enemyPkmnDamageTaken")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turn", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enemyPkmnDamageTaken",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "playerPkmnDamageTaken",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
