"""empty message

Revision ID: e0e458a0e5c7
Revises: 2ea801ef7d6a
Create Date: 2023-11-17 15:05:52.802566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e458a0e5c7'
down_revision = '2ea801ef7d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_moves_learned_by_pokemon',
    sa.Column('pkmn_id', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['pkmn_moves.id'], ),
    sa.ForeignKeyConstraint(['pkmn_id'], ['pkmn.id'], )
    )
    op.create_table('status_moves_learned_by_pokemon',
    sa.Column('pkmn_id', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['pkmn_moves.id'], ),
    sa.ForeignKeyConstraint(['pkmn_id'], ['pkmn.id'], )
    )
    op.drop_table('moves_learned_by_pokemon')
    with op.batch_alter_table('pkmn_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effectChance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target', sa.String(), nullable=False))
        batch_op.alter_column('power',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('accuracy',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn_moves', schema=None) as batch_op:
        batch_op.alter_column('accuracy',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('power',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('target')
        batch_op.drop_column('effectChance')

    op.create_table('moves_learned_by_pokemon',
    sa.Column('pkmn_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('move_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['pkmn_moves.id'], name='moves_learned_by_pokemon_move_id_fkey'),
    sa.ForeignKeyConstraint(['pkmn_id'], ['pkmn.id'], name='moves_learned_by_pokemon_pkmn_id_fkey')
    )
    op.drop_table('status_moves_learned_by_pokemon')
    op.drop_table('damage_moves_learned_by_pokemon')
    # ### end Alembic commands ###
