"""empty message

Revision ID: f9a3cc1410b0
Revises: 12fad2f70e2f
Create Date: 2023-11-14 21:09:43.512941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a3cc1410b0'
down_revision = '12fad2f70e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn', schema=None) as batch_op:
        batch_op.drop_column('form')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pkmn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
